"""add_chosen_colors_and_typography

Revision ID: 239c08f62eef
Revises: 6a913f267254
Create Date: 2026-01-07 16:44:31.671235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239c08f62eef'
down_revision: Union[str, None] = '6a913f267254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_sessions', sa.Column('chosen_colors', sa.Text(), nullable=True))
    op.add_column('extraction_sessions', sa.Column('chosen_typography', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_sessions', 'chosen_typography')
    op.drop_column('extraction_sessions', 'chosen_colors')
    # ### end Alembic commands ###
