"""Add project_description to extraction_sessions

Revision ID: 6a913f267254
Revises: ae68ad73a252
Create Date: 2026-01-07 13:34:12.253232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a913f267254'
down_revision: Union[str, None] = 'ae68ad73a252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_sessions', sa.Column('project_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_sessions', 'project_description')
    # ### end Alembic commands ###
