"""add_interactive_ux_audit_models

Revision ID: 7c75b267f2ba
Revises: 239c08f62eef
Create Date: 2026-01-08 10:20:03.692145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c75b267f2ba'
down_revision: Union[str, None] = '239c08f62eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Add new columns to style_rules for interactive UX rules (check if they exist first)
    inspector = sa.inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('style_rules')]

    if 'rule_category' not in existing_columns:
        op.add_column('style_rules', sa.Column('rule_category', sa.String(), nullable=True, server_default='STATIC'))
    if 'timing_constraint_ms' not in existing_columns:
        op.add_column('style_rules', sa.Column('timing_constraint_ms', sa.Integer(), nullable=True))
    if 'count_property' not in existing_columns:
        op.add_column('style_rules', sa.Column('count_property', sa.String(), nullable=True))
    if 'zone_definition' not in existing_columns:
        op.add_column('style_rules', sa.Column('zone_definition', sa.JSON(), nullable=True))
    if 'pattern_indicators' not in existing_columns:
        op.add_column('style_rules', sa.Column('pattern_indicators', sa.JSON(), nullable=True))

    # Check which tables already exist
    existing_tables = inspector.get_table_names()

    # Create interaction_recordings table if not exists
    if 'interaction_recordings' not in existing_tables:
        op.create_table(
            'interaction_recordings',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('session_id', sa.Integer(), sa.ForeignKey('extraction_sessions.id', ondelete='CASCADE'), nullable=False),
            sa.Column('source_type', sa.String(), nullable=False),
            sa.Column('source_path', sa.String(), nullable=True),
            sa.Column('duration_ms', sa.Integer(), nullable=True),
            sa.Column('frame_count', sa.Integer(), server_default='0'),
            sa.Column('status', sa.String(), server_default='pending'),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
            sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        )

    # Create interaction_frames table if not exists
    if 'interaction_frames' not in existing_tables:
        op.create_table(
            'interaction_frames',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('recording_id', sa.Integer(), sa.ForeignKey('interaction_recordings.id', ondelete='CASCADE'), nullable=False),
            sa.Column('frame_number', sa.Integer(), nullable=False),
            sa.Column('timestamp_ms', sa.Integer(), nullable=False),
            sa.Column('frame_path', sa.String(), nullable=False),
            sa.Column('extracted_values', sa.JSON(), nullable=True),
            sa.Column('extraction_status', sa.String(), server_default='pending'),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        )

    # Create temporal_metrics table if not exists
    if 'temporal_metrics' not in existing_tables:
        op.create_table(
            'temporal_metrics',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('recording_id', sa.Integer(), sa.ForeignKey('interaction_recordings.id', ondelete='CASCADE'), nullable=False),
            sa.Column('metric_type', sa.String(), nullable=False),
            sa.Column('start_frame_id', sa.Integer(), sa.ForeignKey('interaction_frames.id'), nullable=False),
            sa.Column('end_frame_id', sa.Integer(), sa.ForeignKey('interaction_frames.id'), nullable=False),
            sa.Column('duration_ms', sa.Integer(), nullable=False),
            sa.Column('details', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop new tables in reverse order (due to foreign key dependencies)
    op.drop_table('temporal_metrics')
    op.drop_table('interaction_frames')
    op.drop_table('interaction_recordings')

    # Drop new columns from style_rules
    op.drop_column('style_rules', 'pattern_indicators')
    op.drop_column('style_rules', 'zone_definition')
    op.drop_column('style_rules', 'count_property')
    op.drop_column('style_rules', 'timing_constraint_ms')
    op.drop_column('style_rules', 'rule_category')
    # ### end Alembic commands ###
