"""Add multi-question support columns

Revision ID: ae68ad73a252
Revises: 
Create Date: 2026-01-07 10:11:54.803533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae68ad73a252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison_results', sa.Column('question_responses', sa.Text(), nullable=True))
    op.add_column('extraction_sessions', sa.Column('established_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_sessions', 'established_preferences')
    op.drop_column('comparison_results', 'question_responses')
    # ### end Alembic commands ###
